def init_metrics(metrics, pve):
    """
    Initialize counter at 0 for each label combination
    """
    nodes = pve.nodes.get()
    for key in metrics:
        for node in nodes:
            for task_type in pve_task_type:
                metrics[key].labels(type=task_type, node=node["node"])


pve_task_type = [
    "acmedeactivate",
    "acmenewcert",
    "acmerefresh",
    "acmeregister",
    "acmerenew",
    "acmerevoke",
    "acmeupdate",
    "auth-realm-sync",
    "auth-realm-sync-test",
    "cephcreatemds",
    "cephcreatemgr",
    "cephcreatemon",
    "cephcreateosd",
    "cephcreatepool",
    "cephdestroymds",
    "cephdestroymgr",
    "cephdestroymon",
    "cephdestroyosd",
    "cephdestroypool",
    "cephdestroyfs",
    "cephfscreate",
    "cephsetpool",
    "cephsetflags",
    "clustercreate",
    "clusterjoin",
    "dircreate",
    "dirremove",
    "download",
    "hamigrate",
    "hashutdown",
    "hastart",
    "hastop",
    "imgcopy",
    "imgdel",
    "lvmcreate",
    "lvmremove",
    "lvmthincreate",
    "lvmthinremove",
    "migrateall",
    "move_volume",
    "pbs-download",
    "pull_file",
    "push_file",
    "qmclone",
    "qmconfig",
    "qmcreate",
    "qmdelsnapshot",
    "qmdestroy",
    "qmigrate",
    "qmmove",
    "qmpause",
    "qmreboot",
    "qmreset",
    "qmrestore",
    "qmresume",
    "qmrollback",
    "qmshutdown",
    "qmsnapshot",
    "qmstart",
    "qmstop",
    "qmsuspend",
    "qmtemplate",
    "spiceproxy",
    "spiceshell",
    "startall",
    "stopall",
    "unknownimgdel",
    "wipedisk",
    "vncproxy",
    "vncshell",
    "vzclone",
    "vzcreate",
    "vzdelsnapshot",
    "vzdestroy",
    "vzdump",
    "vzmigrate",
    "vzmount",
    "vzreboot",
    "vzrestore",
    "vzresume",
    "vzrollback",
    "vzshutdown",
    "vzsnapshot",
    "vzstart",
    "vzstop",
    "vzsuspend",
    "vztemplate",
    "vzumount",
    "zfscreate",
    "zfsremove",
]
